import { GoogleGenAI } from "@google/genai";
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { Prisma } from "@prisma/client";
import { z } from "zod";
import counterSchema from "@/data/counterSchema";
import { shorteningCounterData } from "@/utils/counter/counterDbFuns";

//responseSchema用
const aiResSchema = z.object({
  answer: z
    .string()
    .describe("Response to the user. Please write it in Markdown format."),
  counters: z
    .array(z.number())
    .describe(
      "An array of counter IDs related to the response. Do not include unrelated counters.",
    ),
});

const ai = new GoogleGenAI({});

export async function POST(request: NextRequest) {
  try {
    // 1. Ask the AI to generate an SQL query suitable for the user's request.

    const { prompt } = await request.json();
    const aiSqlRes = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        systemInstruction: [
          "You are an SQL engineer working with a database of hands-free travel counters in Japan, which will be provided later. The user's travel itinerary will be given in the prompt. Generate an appropriate SQL query fragment to retrieve counters that may be useful during the itinerary.",
          'Output only the part that comes after "SELECT * FROM counter". Do not provide any explanations.',
          `The database uses SQLite and Prisma. The table name is "counter". The schema is as follows:
  ${counterSchema}
  `,
          'When filtering counters by address, use the "カウンター住所_都道府県コード" field. The retrieved data will be processed again later, so perform a broad search at this stage.',
          "Records with is_closed = 1 have already been removed. Therefore, you do not need to handle the is_closed flag in the WHERE clause.",
        ],
      },
    });

    // 2. Search the database using the SQL query generated by the AI.
    // console.log(aiSqlRes.text);
    const dbResult = await prisma.$queryRaw(
      Prisma.raw(`SELECT カウンターID FROM counter ${aiSqlRes.text}`),
    );

    // 3. Provide the AI with the search results and the user's request, and have it generate the final response.
    // console.log(Array.isArray(dbResult) ? dbResult.length : "0件");

    let aiRes;
    if (!Array.isArray(dbResult) || dbResult.length === 0) {
      return NextResponse.json({
        success: false,
        message: "AI API request succeeded (no matching counters found)",
        res: "We couldn't find any hands-free travel counters that fit your itinerary. Please revise your request and try again.",
      });
    } else {
      const idArray: Array<number> = [];
      dbResult.forEach((ele) => {
        idArray.push(ele["カウンターID"]);
      });
      const shortData = await shorteningCounterData(idArray);
      if (shortData === null) {
        throw Error;
      }
      const JSONdata = JSON.stringify(shortData);
      // console.log(shortData)
      aiRes = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
          systemInstruction: [
            `You are an expert on Japan's hands-free travel counters. Several counters that may be relevant to the user's itinerary have already been selected from the database. Based on the following data, create a plan for how the user could use these hands-free travel counters during their trip.
  JSON data (already converted to text):
  ${JSONdata}
  `,
            `If an appropriate schedule can be created, include it in your response. The schedule should generally follow this format:
  (Date and time): Use (counter name) for (service type: storage / same-day delivery / standard delivery / overseas delivery)
  ↓
  (Date and time): Pick up the luggage at (counter name)
  You may modify the format as needed.
  `,
            "You must write 'answer' in English.",
            "If an appropriate schedule cannot be created, simply mention the counters that may be useful. There is no need to force a schedule.",
            "When referring to a counter, include only its name. Unless specifically requested, do not include any additional information such as IDs or addresses in the 'answer'.",
            'Do not include phrases such as "For more details..." or similar expressions.',
          ],
          responseMimeType: "application/json",
          responseJsonSchema: z.toJSONSchema(aiResSchema),
        },
      });
    }

    if (aiRes.text) {
      const parsedAiRes = aiResSchema.parse(JSON.parse(aiRes.text));

      return NextResponse.json({
        success: true,
        message: "AI API request successful",
        res: parsedAiRes.answer,
        counters: parsedAiRes.counters,
      });
    }
  } catch (e) {
    return NextResponse.json({
      success: false,
      message: "AI API request failed",
      res: "An error occurrd. Please try again." + e,
    });
  }
}
